//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Phs.API.paymentexpress {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaymentExpressWSSoap", Namespace="http://PaymentExpress.com")]
    public partial class PaymentExpressWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SubmitTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitTransaction2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Check3dsEnrollmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatus2OperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PaymentExpressWS() {
            this.Url = global::Phs.API.Properties.Settings.Default.Parko_API_paymentexpress_PaymentExpressWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitTransactionCompletedEventHandler SubmitTransactionCompleted;
        
        /// <remarks/>
        public event SubmitTransaction2CompletedEventHandler SubmitTransaction2Completed;
        
        /// <remarks/>
        public event Check3dsEnrollmentCompletedEventHandler Check3dsEnrollmentCompleted;
        
        /// <remarks/>
        public event GetStatusCompletedEventHandler GetStatusCompleted;
        
        /// <remarks/>
        public event GetStatus2CompletedEventHandler GetStatus2Completed;
        
        /// <remarks/>
        public event UpdateCardCompletedEventHandler UpdateCardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PaymentExpress.com/SubmitTransaction", RequestNamespace="http://PaymentExpress.com", ResponseNamespace="http://PaymentExpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionResult2 SubmitTransaction(string postUsername, string postPassword, TransactionDetails transactionDetails) {
            object[] results = this.Invoke("SubmitTransaction", new object[] {
                        postUsername,
                        postPassword,
                        transactionDetails});
            return ((TransactionResult2)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitTransactionAsync(string postUsername, string postPassword, TransactionDetails transactionDetails) {
            this.SubmitTransactionAsync(postUsername, postPassword, transactionDetails, null);
        }
        
        /// <remarks/>
        public void SubmitTransactionAsync(string postUsername, string postPassword, TransactionDetails transactionDetails, object userState) {
            if ((this.SubmitTransactionOperationCompleted == null)) {
                this.SubmitTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitTransactionOperationCompleted);
            }
            this.InvokeAsync("SubmitTransaction", new object[] {
                        postUsername,
                        postPassword,
                        transactionDetails}, this.SubmitTransactionOperationCompleted, userState);
        }
        
        private void OnSubmitTransactionOperationCompleted(object arg) {
            if ((this.SubmitTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitTransactionCompleted(this, new SubmitTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PaymentExpress.com/SubmitTransaction2", RequestNamespace="http://PaymentExpress.com", ResponseNamespace="http://PaymentExpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionResult2 SubmitTransaction2(string postUsername, string postPassword, TransactionDetails transactionDetails) {
            object[] results = this.Invoke("SubmitTransaction2", new object[] {
                        postUsername,
                        postPassword,
                        transactionDetails});
            return ((TransactionResult2)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitTransaction2Async(string postUsername, string postPassword, TransactionDetails transactionDetails) {
            this.SubmitTransaction2Async(postUsername, postPassword, transactionDetails, null);
        }
        
        /// <remarks/>
        public void SubmitTransaction2Async(string postUsername, string postPassword, TransactionDetails transactionDetails, object userState) {
            if ((this.SubmitTransaction2OperationCompleted == null)) {
                this.SubmitTransaction2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitTransaction2OperationCompleted);
            }
            this.InvokeAsync("SubmitTransaction2", new object[] {
                        postUsername,
                        postPassword,
                        transactionDetails}, this.SubmitTransaction2OperationCompleted, userState);
        }
        
        private void OnSubmitTransaction2OperationCompleted(object arg) {
            if ((this.SubmitTransaction2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitTransaction2Completed(this, new SubmitTransaction2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PaymentExpress.com/Check3dsEnrollment", RequestNamespace="http://PaymentExpress.com", ResponseNamespace="http://PaymentExpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnrolmentCheckResult Check3dsEnrollment(string postUsername, string postPassword, EnrolmentCheckRequest transactionDetails) {
            object[] results = this.Invoke("Check3dsEnrollment", new object[] {
                        postUsername,
                        postPassword,
                        transactionDetails});
            return ((EnrolmentCheckResult)(results[0]));
        }
        
        /// <remarks/>
        public void Check3dsEnrollmentAsync(string postUsername, string postPassword, EnrolmentCheckRequest transactionDetails) {
            this.Check3dsEnrollmentAsync(postUsername, postPassword, transactionDetails, null);
        }
        
        /// <remarks/>
        public void Check3dsEnrollmentAsync(string postUsername, string postPassword, EnrolmentCheckRequest transactionDetails, object userState) {
            if ((this.Check3dsEnrollmentOperationCompleted == null)) {
                this.Check3dsEnrollmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck3dsEnrollmentOperationCompleted);
            }
            this.InvokeAsync("Check3dsEnrollment", new object[] {
                        postUsername,
                        postPassword,
                        transactionDetails}, this.Check3dsEnrollmentOperationCompleted, userState);
        }
        
        private void OnCheck3dsEnrollmentOperationCompleted(object arg) {
            if ((this.Check3dsEnrollmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check3dsEnrollmentCompleted(this, new Check3dsEnrollmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PaymentExpress.com/GetStatus", RequestNamespace="http://PaymentExpress.com", ResponseNamespace="http://PaymentExpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionResult2 GetStatus(string postUsername, string postPassword, string txnRef) {
            object[] results = this.Invoke("GetStatus", new object[] {
                        postUsername,
                        postPassword,
                        txnRef});
            return ((TransactionResult2)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusAsync(string postUsername, string postPassword, string txnRef) {
            this.GetStatusAsync(postUsername, postPassword, txnRef, null);
        }
        
        /// <remarks/>
        public void GetStatusAsync(string postUsername, string postPassword, string txnRef, object userState) {
            if ((this.GetStatusOperationCompleted == null)) {
                this.GetStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusOperationCompleted);
            }
            this.InvokeAsync("GetStatus", new object[] {
                        postUsername,
                        postPassword,
                        txnRef}, this.GetStatusOperationCompleted, userState);
        }
        
        private void OnGetStatusOperationCompleted(object arg) {
            if ((this.GetStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusCompleted(this, new GetStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PaymentExpress.com/GetStatus2", RequestNamespace="http://PaymentExpress.com", ResponseNamespace="http://PaymentExpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionResult2 GetStatus2(string postUsername, string postPassword, string txnRef) {
            object[] results = this.Invoke("GetStatus2", new object[] {
                        postUsername,
                        postPassword,
                        txnRef});
            return ((TransactionResult2)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatus2Async(string postUsername, string postPassword, string txnRef) {
            this.GetStatus2Async(postUsername, postPassword, txnRef, null);
        }
        
        /// <remarks/>
        public void GetStatus2Async(string postUsername, string postPassword, string txnRef, object userState) {
            if ((this.GetStatus2OperationCompleted == null)) {
                this.GetStatus2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatus2OperationCompleted);
            }
            this.InvokeAsync("GetStatus2", new object[] {
                        postUsername,
                        postPassword,
                        txnRef}, this.GetStatus2OperationCompleted, userState);
        }
        
        private void OnGetStatus2OperationCompleted(object arg) {
            if ((this.GetStatus2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatus2Completed(this, new GetStatus2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PaymentExpress.com/UpdateCard", RequestNamespace="http://PaymentExpress.com", ResponseNamespace="http://PaymentExpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateCard(string postUsername, string postPassword, string cardDetails) {
            object[] results = this.Invoke("UpdateCard", new object[] {
                        postUsername,
                        postPassword,
                        cardDetails});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCardAsync(string postUsername, string postPassword, string cardDetails) {
            this.UpdateCardAsync(postUsername, postPassword, cardDetails, null);
        }
        
        /// <remarks/>
        public void UpdateCardAsync(string postUsername, string postPassword, string cardDetails, object userState) {
            if ((this.UpdateCardOperationCompleted == null)) {
                this.UpdateCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCardOperationCompleted);
            }
            this.InvokeAsync("UpdateCard", new object[] {
                        postUsername,
                        postPassword,
                        cardDetails}, this.UpdateCardOperationCompleted, userState);
        }
        
        private void OnUpdateCardOperationCompleted(object arg) {
            if ((this.UpdateCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCardCompleted(this, new UpdateCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PaymentExpress.com")]
    public partial class TransactionDetails {
        
        private string amountField;
        
        private string billingIdField;
        
        private string cardHolderNameField;
        
        private string cardNumberField;
        
        private string clientInfoField;
        
        private string cvc2Field;
        
        private string dateExpiryField;
        
        private string dpsBillingIdField;
        
        private string dpsTxnRefField;
        
        private string enableAddBillCardField;
        
        private string enablePaxInfoField;
        
        private string inputCurrencyField;
        
        private string merchantReferenceField;
        
        private string paxCarrierField;
        
        private string paxCarrier2Field;
        
        private string paxCarrier3Field;
        
        private string paxCarrier4Field;
        
        private string paxDateDepartField;
        
        private string paxDate2Field;
        
        private string paxDate3Field;
        
        private string paxDate4Field;
        
        private string paxTime1Field;
        
        private string paxTime2Field;
        
        private string paxTime3Field;
        
        private string paxTime4Field;
        
        private string paxLeg1Field;
        
        private string paxLeg2Field;
        
        private string paxLeg3Field;
        
        private string paxLeg4Field;
        
        private string paxClass1Field;
        
        private string paxClass2Field;
        
        private string paxClass3Field;
        
        private string paxClass4Field;
        
        private string paxStopOverCode1Field;
        
        private string paxStopOverCode2Field;
        
        private string paxStopOverCode3Field;
        
        private string paxStopOverCode4Field;
        
        private string paxFareBasis1Field;
        
        private string paxFareBasis2Field;
        
        private string paxFareBasis3Field;
        
        private string paxFareBasis4Field;
        
        private string paxFlightNumber1Field;
        
        private string paxFlightNumber2Field;
        
        private string paxFlightNumber3Field;
        
        private string paxFlightNumber4Field;
        
        private string paxNameField;
        
        private string paxOriginField;
        
        private string paxTicketNumberField;
        
        private string paxTravelAgentInfoField;
        
        private string txnData1Field;
        
        private string txnData2Field;
        
        private string txnData3Field;
        
        private string txnRefField;
        
        private string txnTypeField;
        
        private string dateStartField;
        
        private string issueNumberField;
        
        private string enableAvsDataField;
        
        private string avsActionField;
        
        private string avsPostCodeField;
        
        private string avsStreetAddressField;
        
        private string enable3DSecureField;
        
        private string paResField;
        
        private string clientTypeField;
        
        private string iccDataField;
        
        private string deviceIdField;
        
        private string cardNumber2Field;
        
        private string track2Field;
        
        private string cvc2PresenceField;
        
        private NameValueField[] extendedDataField;
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string billingId {
            get {
                return this.billingIdField;
            }
            set {
                this.billingIdField = value;
            }
        }
        
        /// <remarks/>
        public string cardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string clientInfo {
            get {
                return this.clientInfoField;
            }
            set {
                this.clientInfoField = value;
            }
        }
        
        /// <remarks/>
        public string cvc2 {
            get {
                return this.cvc2Field;
            }
            set {
                this.cvc2Field = value;
            }
        }
        
        /// <remarks/>
        public string dateExpiry {
            get {
                return this.dateExpiryField;
            }
            set {
                this.dateExpiryField = value;
            }
        }
        
        /// <remarks/>
        public string dpsBillingId {
            get {
                return this.dpsBillingIdField;
            }
            set {
                this.dpsBillingIdField = value;
            }
        }
        
        /// <remarks/>
        public string dpsTxnRef {
            get {
                return this.dpsTxnRefField;
            }
            set {
                this.dpsTxnRefField = value;
            }
        }
        
        /// <remarks/>
        public string enableAddBillCard {
            get {
                return this.enableAddBillCardField;
            }
            set {
                this.enableAddBillCardField = value;
            }
        }
        
        /// <remarks/>
        public string enablePaxInfo {
            get {
                return this.enablePaxInfoField;
            }
            set {
                this.enablePaxInfoField = value;
            }
        }
        
        /// <remarks/>
        public string inputCurrency {
            get {
                return this.inputCurrencyField;
            }
            set {
                this.inputCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string merchantReference {
            get {
                return this.merchantReferenceField;
            }
            set {
                this.merchantReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string paxCarrier {
            get {
                return this.paxCarrierField;
            }
            set {
                this.paxCarrierField = value;
            }
        }
        
        /// <remarks/>
        public string paxCarrier2 {
            get {
                return this.paxCarrier2Field;
            }
            set {
                this.paxCarrier2Field = value;
            }
        }
        
        /// <remarks/>
        public string paxCarrier3 {
            get {
                return this.paxCarrier3Field;
            }
            set {
                this.paxCarrier3Field = value;
            }
        }
        
        /// <remarks/>
        public string paxCarrier4 {
            get {
                return this.paxCarrier4Field;
            }
            set {
                this.paxCarrier4Field = value;
            }
        }
        
        /// <remarks/>
        public string paxDateDepart {
            get {
                return this.paxDateDepartField;
            }
            set {
                this.paxDateDepartField = value;
            }
        }
        
        /// <remarks/>
        public string paxDate2 {
            get {
                return this.paxDate2Field;
            }
            set {
                this.paxDate2Field = value;
            }
        }
        
        /// <remarks/>
        public string paxDate3 {
            get {
                return this.paxDate3Field;
            }
            set {
                this.paxDate3Field = value;
            }
        }
        
        /// <remarks/>
        public string paxDate4 {
            get {
                return this.paxDate4Field;
            }
            set {
                this.paxDate4Field = value;
            }
        }
        
        /// <remarks/>
        public string paxTime1 {
            get {
                return this.paxTime1Field;
            }
            set {
                this.paxTime1Field = value;
            }
        }
        
        /// <remarks/>
        public string paxTime2 {
            get {
                return this.paxTime2Field;
            }
            set {
                this.paxTime2Field = value;
            }
        }
        
        /// <remarks/>
        public string paxTime3 {
            get {
                return this.paxTime3Field;
            }
            set {
                this.paxTime3Field = value;
            }
        }
        
        /// <remarks/>
        public string paxTime4 {
            get {
                return this.paxTime4Field;
            }
            set {
                this.paxTime4Field = value;
            }
        }
        
        /// <remarks/>
        public string paxLeg1 {
            get {
                return this.paxLeg1Field;
            }
            set {
                this.paxLeg1Field = value;
            }
        }
        
        /// <remarks/>
        public string paxLeg2 {
            get {
                return this.paxLeg2Field;
            }
            set {
                this.paxLeg2Field = value;
            }
        }
        
        /// <remarks/>
        public string paxLeg3 {
            get {
                return this.paxLeg3Field;
            }
            set {
                this.paxLeg3Field = value;
            }
        }
        
        /// <remarks/>
        public string paxLeg4 {
            get {
                return this.paxLeg4Field;
            }
            set {
                this.paxLeg4Field = value;
            }
        }
        
        /// <remarks/>
        public string paxClass1 {
            get {
                return this.paxClass1Field;
            }
            set {
                this.paxClass1Field = value;
            }
        }
        
        /// <remarks/>
        public string paxClass2 {
            get {
                return this.paxClass2Field;
            }
            set {
                this.paxClass2Field = value;
            }
        }
        
        /// <remarks/>
        public string paxClass3 {
            get {
                return this.paxClass3Field;
            }
            set {
                this.paxClass3Field = value;
            }
        }
        
        /// <remarks/>
        public string paxClass4 {
            get {
                return this.paxClass4Field;
            }
            set {
                this.paxClass4Field = value;
            }
        }
        
        /// <remarks/>
        public string paxStopOverCode1 {
            get {
                return this.paxStopOverCode1Field;
            }
            set {
                this.paxStopOverCode1Field = value;
            }
        }
        
        /// <remarks/>
        public string paxStopOverCode2 {
            get {
                return this.paxStopOverCode2Field;
            }
            set {
                this.paxStopOverCode2Field = value;
            }
        }
        
        /// <remarks/>
        public string paxStopOverCode3 {
            get {
                return this.paxStopOverCode3Field;
            }
            set {
                this.paxStopOverCode3Field = value;
            }
        }
        
        /// <remarks/>
        public string paxStopOverCode4 {
            get {
                return this.paxStopOverCode4Field;
            }
            set {
                this.paxStopOverCode4Field = value;
            }
        }
        
        /// <remarks/>
        public string paxFareBasis1 {
            get {
                return this.paxFareBasis1Field;
            }
            set {
                this.paxFareBasis1Field = value;
            }
        }
        
        /// <remarks/>
        public string paxFareBasis2 {
            get {
                return this.paxFareBasis2Field;
            }
            set {
                this.paxFareBasis2Field = value;
            }
        }
        
        /// <remarks/>
        public string paxFareBasis3 {
            get {
                return this.paxFareBasis3Field;
            }
            set {
                this.paxFareBasis3Field = value;
            }
        }
        
        /// <remarks/>
        public string paxFareBasis4 {
            get {
                return this.paxFareBasis4Field;
            }
            set {
                this.paxFareBasis4Field = value;
            }
        }
        
        /// <remarks/>
        public string paxFlightNumber1 {
            get {
                return this.paxFlightNumber1Field;
            }
            set {
                this.paxFlightNumber1Field = value;
            }
        }
        
        /// <remarks/>
        public string paxFlightNumber2 {
            get {
                return this.paxFlightNumber2Field;
            }
            set {
                this.paxFlightNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string paxFlightNumber3 {
            get {
                return this.paxFlightNumber3Field;
            }
            set {
                this.paxFlightNumber3Field = value;
            }
        }
        
        /// <remarks/>
        public string paxFlightNumber4 {
            get {
                return this.paxFlightNumber4Field;
            }
            set {
                this.paxFlightNumber4Field = value;
            }
        }
        
        /// <remarks/>
        public string paxName {
            get {
                return this.paxNameField;
            }
            set {
                this.paxNameField = value;
            }
        }
        
        /// <remarks/>
        public string paxOrigin {
            get {
                return this.paxOriginField;
            }
            set {
                this.paxOriginField = value;
            }
        }
        
        /// <remarks/>
        public string paxTicketNumber {
            get {
                return this.paxTicketNumberField;
            }
            set {
                this.paxTicketNumberField = value;
            }
        }
        
        /// <remarks/>
        public string paxTravelAgentInfo {
            get {
                return this.paxTravelAgentInfoField;
            }
            set {
                this.paxTravelAgentInfoField = value;
            }
        }
        
        /// <remarks/>
        public string txnData1 {
            get {
                return this.txnData1Field;
            }
            set {
                this.txnData1Field = value;
            }
        }
        
        /// <remarks/>
        public string txnData2 {
            get {
                return this.txnData2Field;
            }
            set {
                this.txnData2Field = value;
            }
        }
        
        /// <remarks/>
        public string txnData3 {
            get {
                return this.txnData3Field;
            }
            set {
                this.txnData3Field = value;
            }
        }
        
        /// <remarks/>
        public string txnRef {
            get {
                return this.txnRefField;
            }
            set {
                this.txnRefField = value;
            }
        }
        
        /// <remarks/>
        public string txnType {
            get {
                return this.txnTypeField;
            }
            set {
                this.txnTypeField = value;
            }
        }
        
        /// <remarks/>
        public string dateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        public string issueNumber {
            get {
                return this.issueNumberField;
            }
            set {
                this.issueNumberField = value;
            }
        }
        
        /// <remarks/>
        public string enableAvsData {
            get {
                return this.enableAvsDataField;
            }
            set {
                this.enableAvsDataField = value;
            }
        }
        
        /// <remarks/>
        public string avsAction {
            get {
                return this.avsActionField;
            }
            set {
                this.avsActionField = value;
            }
        }
        
        /// <remarks/>
        public string avsPostCode {
            get {
                return this.avsPostCodeField;
            }
            set {
                this.avsPostCodeField = value;
            }
        }
        
        /// <remarks/>
        public string avsStreetAddress {
            get {
                return this.avsStreetAddressField;
            }
            set {
                this.avsStreetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string enable3DSecure {
            get {
                return this.enable3DSecureField;
            }
            set {
                this.enable3DSecureField = value;
            }
        }
        
        /// <remarks/>
        public string paRes {
            get {
                return this.paResField;
            }
            set {
                this.paResField = value;
            }
        }
        
        /// <remarks/>
        public string clientType {
            get {
                return this.clientTypeField;
            }
            set {
                this.clientTypeField = value;
            }
        }
        
        /// <remarks/>
        public string iccData {
            get {
                return this.iccDataField;
            }
            set {
                this.iccDataField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string cardNumber2 {
            get {
                return this.cardNumber2Field;
            }
            set {
                this.cardNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string track2 {
            get {
                return this.track2Field;
            }
            set {
                this.track2Field = value;
            }
        }
        
        /// <remarks/>
        public string cvc2Presence {
            get {
                return this.cvc2PresenceField;
            }
            set {
                this.cvc2PresenceField = value;
            }
        }
        
        /// <remarks/>
        public NameValueField[] extendedData {
            get {
                return this.extendedDataField;
            }
            set {
                this.extendedDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PaymentExpress.com")]
    public partial class NameValueField {
        
        private string fieldNameField;
        
        private string fieldValueField;
        
        /// <remarks/>
        public string fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string fieldValue {
            get {
                return this.fieldValueField;
            }
            set {
                this.fieldValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PaymentExpress.com")]
    public partial class EnrolmentCheckResult {
        
        private string enrolledField;
        
        private string paReqField;
        
        private string acsURLField;
        
        /// <remarks/>
        public string enrolled {
            get {
                return this.enrolledField;
            }
            set {
                this.enrolledField = value;
            }
        }
        
        /// <remarks/>
        public string paReq {
            get {
                return this.paReqField;
            }
            set {
                this.paReqField = value;
            }
        }
        
        /// <remarks/>
        public string acsURL {
            get {
                return this.acsURLField;
            }
            set {
                this.acsURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PaymentExpress.com")]
    public partial class EnrolmentCheckRequest {
        
        private string amountField;
        
        private string cardNumberField;
        
        private string dateExpiryField;
        
        private string txnDescriptionField;
        
        private string txnRefField;
        
        private string currencyField;
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string dateExpiry {
            get {
                return this.dateExpiryField;
            }
            set {
                this.dateExpiryField = value;
            }
        }
        
        /// <remarks/>
        public string txnDescription {
            get {
                return this.txnDescriptionField;
            }
            set {
                this.txnDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string txnRef {
            get {
                return this.txnRefField;
            }
            set {
                this.txnRefField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PaymentExpress.com")]
    public partial class riskRuleMatch {
        
        private string matchedAmountField;
        
        private int matchedTransactionCountField;
        
        private string nameField;
        
        private string typeField;
        
        private string actionField;
        
        private int periodField;
        
        private string includedTransactionsField;
        
        private string amountLimitField;
        
        private int transactionCountLimitField;
        
        /// <remarks/>
        public string matchedAmount {
            get {
                return this.matchedAmountField;
            }
            set {
                this.matchedAmountField = value;
            }
        }
        
        /// <remarks/>
        public int matchedTransactionCount {
            get {
                return this.matchedTransactionCountField;
            }
            set {
                this.matchedTransactionCountField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public int period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        public string includedTransactions {
            get {
                return this.includedTransactionsField;
            }
            set {
                this.includedTransactionsField = value;
            }
        }
        
        /// <remarks/>
        public string amountLimit {
            get {
                return this.amountLimitField;
            }
            set {
                this.amountLimitField = value;
            }
        }
        
        /// <remarks/>
        public int transactionCountLimit {
            get {
                return this.transactionCountLimitField;
            }
            set {
                this.transactionCountLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PaymentExpress.com")]
    public partial class TransactionResult2 {
        
        private string acquirerRecoField;
        
        private string acquirerResponseTextField;
        
        private string amountField;
        
        private string authCodeField;
        
        private string authorizedField;
        
        private string billingIdField;
        
        private string cardHolderHelpTextField;
        
        private string cardHolderNameField;
        
        private string cardHolderResponseDescriptionField;
        
        private string cardHolderResponseTextField;
        
        private string cardNameField;
        
        private string cardNumberField;
        
        private string currencyIdField;
        
        private string currencyNameField;
        
        private string currencyRateField;
        
        private string cvc2Field;
        
        private string dateExpiryField;
        
        private string dateSettlementField;
        
        private string dpsBillingIdField;
        
        private string dpsTxnRefField;
        
        private string helpTextField;
        
        private string merchantHelpTextField;
        
        private string merchantReferenceField;
        
        private string merchantResponseDescriptionField;
        
        private string merchantResponseTextField;
        
        private string recoField;
        
        private string responseTextField;
        
        private string retryField;
        
        private string statusRequiredField;
        
        private string testModeField;
        
        private string txnRefField;
        
        private string txnTypeField;
        
        private string iccDataField;
        
        private string cardNumber2Field;
        
        private string issuerCountryIdField;
        
        private string txnMacField;
        
        private string cvc2ResultCodeField;
        
        private riskRuleMatch[] riskRuleMatchesField;
        
        private NameValueField[] extendedDataField;
        
        /// <remarks/>
        public string acquirerReco {
            get {
                return this.acquirerRecoField;
            }
            set {
                this.acquirerRecoField = value;
            }
        }
        
        /// <remarks/>
        public string acquirerResponseText {
            get {
                return this.acquirerResponseTextField;
            }
            set {
                this.acquirerResponseTextField = value;
            }
        }
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        public string authorized {
            get {
                return this.authorizedField;
            }
            set {
                this.authorizedField = value;
            }
        }
        
        /// <remarks/>
        public string billingId {
            get {
                return this.billingIdField;
            }
            set {
                this.billingIdField = value;
            }
        }
        
        /// <remarks/>
        public string cardHolderHelpText {
            get {
                return this.cardHolderHelpTextField;
            }
            set {
                this.cardHolderHelpTextField = value;
            }
        }
        
        /// <remarks/>
        public string cardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        public string cardHolderResponseDescription {
            get {
                return this.cardHolderResponseDescriptionField;
            }
            set {
                this.cardHolderResponseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string cardHolderResponseText {
            get {
                return this.cardHolderResponseTextField;
            }
            set {
                this.cardHolderResponseTextField = value;
            }
        }
        
        /// <remarks/>
        public string cardName {
            get {
                return this.cardNameField;
            }
            set {
                this.cardNameField = value;
            }
        }
        
        /// <remarks/>
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string currencyId {
            get {
                return this.currencyIdField;
            }
            set {
                this.currencyIdField = value;
            }
        }
        
        /// <remarks/>
        public string currencyName {
            get {
                return this.currencyNameField;
            }
            set {
                this.currencyNameField = value;
            }
        }
        
        /// <remarks/>
        public string currencyRate {
            get {
                return this.currencyRateField;
            }
            set {
                this.currencyRateField = value;
            }
        }
        
        /// <remarks/>
        public string cvc2 {
            get {
                return this.cvc2Field;
            }
            set {
                this.cvc2Field = value;
            }
        }
        
        /// <remarks/>
        public string dateExpiry {
            get {
                return this.dateExpiryField;
            }
            set {
                this.dateExpiryField = value;
            }
        }
        
        /// <remarks/>
        public string dateSettlement {
            get {
                return this.dateSettlementField;
            }
            set {
                this.dateSettlementField = value;
            }
        }
        
        /// <remarks/>
        public string dpsBillingId {
            get {
                return this.dpsBillingIdField;
            }
            set {
                this.dpsBillingIdField = value;
            }
        }
        
        /// <remarks/>
        public string dpsTxnRef {
            get {
                return this.dpsTxnRefField;
            }
            set {
                this.dpsTxnRefField = value;
            }
        }
        
        /// <remarks/>
        public string helpText {
            get {
                return this.helpTextField;
            }
            set {
                this.helpTextField = value;
            }
        }
        
        /// <remarks/>
        public string merchantHelpText {
            get {
                return this.merchantHelpTextField;
            }
            set {
                this.merchantHelpTextField = value;
            }
        }
        
        /// <remarks/>
        public string merchantReference {
            get {
                return this.merchantReferenceField;
            }
            set {
                this.merchantReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string merchantResponseDescription {
            get {
                return this.merchantResponseDescriptionField;
            }
            set {
                this.merchantResponseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string merchantResponseText {
            get {
                return this.merchantResponseTextField;
            }
            set {
                this.merchantResponseTextField = value;
            }
        }
        
        /// <remarks/>
        public string reco {
            get {
                return this.recoField;
            }
            set {
                this.recoField = value;
            }
        }
        
        /// <remarks/>
        public string responseText {
            get {
                return this.responseTextField;
            }
            set {
                this.responseTextField = value;
            }
        }
        
        /// <remarks/>
        public string retry {
            get {
                return this.retryField;
            }
            set {
                this.retryField = value;
            }
        }
        
        /// <remarks/>
        public string statusRequired {
            get {
                return this.statusRequiredField;
            }
            set {
                this.statusRequiredField = value;
            }
        }
        
        /// <remarks/>
        public string testMode {
            get {
                return this.testModeField;
            }
            set {
                this.testModeField = value;
            }
        }
        
        /// <remarks/>
        public string txnRef {
            get {
                return this.txnRefField;
            }
            set {
                this.txnRefField = value;
            }
        }
        
        /// <remarks/>
        public string txnType {
            get {
                return this.txnTypeField;
            }
            set {
                this.txnTypeField = value;
            }
        }
        
        /// <remarks/>
        public string iccData {
            get {
                return this.iccDataField;
            }
            set {
                this.iccDataField = value;
            }
        }
        
        /// <remarks/>
        public string cardNumber2 {
            get {
                return this.cardNumber2Field;
            }
            set {
                this.cardNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string issuerCountryId {
            get {
                return this.issuerCountryIdField;
            }
            set {
                this.issuerCountryIdField = value;
            }
        }
        
        /// <remarks/>
        public string txnMac {
            get {
                return this.txnMacField;
            }
            set {
                this.txnMacField = value;
            }
        }
        
        /// <remarks/>
        public string cvc2ResultCode {
            get {
                return this.cvc2ResultCodeField;
            }
            set {
                this.cvc2ResultCodeField = value;
            }
        }
        
        /// <remarks/>
        public riskRuleMatch[] riskRuleMatches {
            get {
                return this.riskRuleMatchesField;
            }
            set {
                this.riskRuleMatchesField = value;
            }
        }
        
        /// <remarks/>
        public NameValueField[] extendedData {
            get {
                return this.extendedDataField;
            }
            set {
                this.extendedDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SubmitTransactionCompletedEventHandler(object sender, SubmitTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionResult2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SubmitTransaction2CompletedEventHandler(object sender, SubmitTransaction2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitTransaction2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitTransaction2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionResult2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Check3dsEnrollmentCompletedEventHandler(object sender, Check3dsEnrollmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check3dsEnrollmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check3dsEnrollmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnrolmentCheckResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnrolmentCheckResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetStatusCompletedEventHandler(object sender, GetStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionResult2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetStatus2CompletedEventHandler(object sender, GetStatus2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatus2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatus2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionResult2)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCardCompletedEventHandler(object sender, UpdateCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591