//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Phs.API.pxfusion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPxFusion", Namespace="http://paymentexpress.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameValueField))]
    public partial class PxFusion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTransactionIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PxFusion() {
            this.Url = global::Phs.API.Properties.Settings.Default.Parko_API_pxfusion_PxFusion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTransactionIdCompletedEventHandler GetTransactionIdCompleted;
        
        /// <remarks/>
        public event CancelTransactionCompletedEventHandler CancelTransactionCompleted;
        
        /// <remarks/>
        public event GetTransactionCompletedEventHandler GetTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://paymentexpress.com/IPxFusion/GetTransactionId", RequestNamespace="http://paymentexpress.com", ResponseNamespace="http://paymentexpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TransactionId GetTransactionId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TransactionDetails tranDetail) {
            object[] results = this.Invoke("GetTransactionId", new object[] {
                        username,
                        password,
                        tranDetail});
            return ((TransactionId)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionIdAsync(string username, string password, TransactionDetails tranDetail) {
            this.GetTransactionIdAsync(username, password, tranDetail, null);
        }
        
        /// <remarks/>
        public void GetTransactionIdAsync(string username, string password, TransactionDetails tranDetail, object userState) {
            if ((this.GetTransactionIdOperationCompleted == null)) {
                this.GetTransactionIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionIdOperationCompleted);
            }
            this.InvokeAsync("GetTransactionId", new object[] {
                        username,
                        password,
                        tranDetail}, this.GetTransactionIdOperationCompleted, userState);
        }
        
        private void OnGetTransactionIdOperationCompleted(object arg) {
            if ((this.GetTransactionIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionIdCompleted(this, new GetTransactionIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://paymentexpress.com/IPxFusion/CancelTransaction", RequestNamespace="http://paymentexpress.com", ResponseNamespace="http://paymentexpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelTransaction([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string transactionId, out bool CancelTransactionResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CancelTransactionResultSpecified) {
            object[] results = this.Invoke("CancelTransaction", new object[] {
                        username,
                        password,
                        transactionId});
            CancelTransactionResult = ((bool)(results[0]));
            CancelTransactionResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CancelTransactionAsync(string username, string password, string transactionId) {
            this.CancelTransactionAsync(username, password, transactionId, null);
        }
        
        /// <remarks/>
        public void CancelTransactionAsync(string username, string password, string transactionId, object userState) {
            if ((this.CancelTransactionOperationCompleted == null)) {
                this.CancelTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelTransactionOperationCompleted);
            }
            this.InvokeAsync("CancelTransaction", new object[] {
                        username,
                        password,
                        transactionId}, this.CancelTransactionOperationCompleted, userState);
        }
        
        private void OnCancelTransactionOperationCompleted(object arg) {
            if ((this.CancelTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelTransactionCompleted(this, new CancelTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://paymentexpress.com/IPxFusion/GetTransaction", RequestNamespace="http://paymentexpress.com", ResponseNamespace="http://paymentexpress.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TransactionResult GetTransaction([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string transactionId) {
            object[] results = this.Invoke("GetTransaction", new object[] {
                        username,
                        password,
                        transactionId});
            return ((TransactionResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionAsync(string username, string password, string transactionId) {
            this.GetTransactionAsync(username, password, transactionId, null);
        }
        
        /// <remarks/>
        public void GetTransactionAsync(string username, string password, string transactionId, object userState) {
            if ((this.GetTransactionOperationCompleted == null)) {
                this.GetTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionOperationCompleted);
            }
            this.InvokeAsync("GetTransaction", new object[] {
                        username,
                        password,
                        transactionId}, this.GetTransactionOperationCompleted, userState);
        }
        
        private void OnGetTransactionOperationCompleted(object arg) {
            if ((this.GetTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionCompleted(this, new GetTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paymentexpress.com")]
    public partial class TransactionDetails {
        
        private string amountField;
        
        private string avsActionField;
        
        private string avsPostCodeField;
        
        private string avsStreetAddressField;
        
        private string billingIdField;
        
        private string currencyField;
        
        private string dateStartField;
        
        private bool enableAddBillCardField;
        
        private bool enableAddBillCardFieldSpecified;
        
        private bool enableAvsDataField;
        
        private bool enableAvsDataFieldSpecified;
        
        private bool enableMandatoryCvc2Field;
        
        private bool enableMandatoryCvc2FieldSpecified;
        
        private bool enablePaxInfoField;
        
        private bool enablePaxInfoFieldSpecified;
        
        private string merchantReferenceField;
        
        private string paxCarrierField;
        
        private string paxCarrier2Field;
        
        private string paxCarrier3Field;
        
        private string paxCarrier4Field;
        
        private string paxClass1Field;
        
        private string paxClass2Field;
        
        private string paxClass3Field;
        
        private string paxClass4Field;
        
        private string paxDate2Field;
        
        private string paxDate3Field;
        
        private string paxDate4Field;
        
        private string paxDateDepartField;
        
        private string paxFareBasis1Field;
        
        private string paxFareBasis2Field;
        
        private string paxFareBasis3Field;
        
        private string paxFareBasis4Field;
        
        private string paxFlightNumber1Field;
        
        private string paxFlightNumber2Field;
        
        private string paxFlightNumber3Field;
        
        private string paxFlightNumber4Field;
        
        private string paxLeg1Field;
        
        private string paxLeg2Field;
        
        private string paxLeg3Field;
        
        private string paxLeg4Field;
        
        private string paxNameField;
        
        private string paxOriginField;
        
        private string paxStopOverCode1Field;
        
        private string paxStopOverCode2Field;
        
        private string paxStopOverCode3Field;
        
        private string paxStopOverCode4Field;
        
        private string paxTicketNumberField;
        
        private string paxTime1Field;
        
        private string paxTime2Field;
        
        private string paxTime3Field;
        
        private string paxTime4Field;
        
        private string paxTravelAgentInfoField;
        
        private string returnUrlField;
        
        private System.DateTime timeoutField;
        
        private bool timeoutFieldSpecified;
        
        private transactionDetailsField[] transactionDetailsFieldsField;
        
        private string txnData1Field;
        
        private string txnData2Field;
        
        private string txnData3Field;
        
        private string txnRefField;
        
        private string txnTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string avsAction {
            get {
                return this.avsActionField;
            }
            set {
                this.avsActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string avsPostCode {
            get {
                return this.avsPostCodeField;
            }
            set {
                this.avsPostCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string avsStreetAddress {
            get {
                return this.avsStreetAddressField;
            }
            set {
                this.avsStreetAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string billingId {
            get {
                return this.billingIdField;
            }
            set {
                this.billingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        public bool enableAddBillCard {
            get {
                return this.enableAddBillCardField;
            }
            set {
                this.enableAddBillCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enableAddBillCardSpecified {
            get {
                return this.enableAddBillCardFieldSpecified;
            }
            set {
                this.enableAddBillCardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool enableAvsData {
            get {
                return this.enableAvsDataField;
            }
            set {
                this.enableAvsDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enableAvsDataSpecified {
            get {
                return this.enableAvsDataFieldSpecified;
            }
            set {
                this.enableAvsDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool enableMandatoryCvc2 {
            get {
                return this.enableMandatoryCvc2Field;
            }
            set {
                this.enableMandatoryCvc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enableMandatoryCvc2Specified {
            get {
                return this.enableMandatoryCvc2FieldSpecified;
            }
            set {
                this.enableMandatoryCvc2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool enablePaxInfo {
            get {
                return this.enablePaxInfoField;
            }
            set {
                this.enablePaxInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enablePaxInfoSpecified {
            get {
                return this.enablePaxInfoFieldSpecified;
            }
            set {
                this.enablePaxInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantReference {
            get {
                return this.merchantReferenceField;
            }
            set {
                this.merchantReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxCarrier {
            get {
                return this.paxCarrierField;
            }
            set {
                this.paxCarrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxCarrier2 {
            get {
                return this.paxCarrier2Field;
            }
            set {
                this.paxCarrier2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxCarrier3 {
            get {
                return this.paxCarrier3Field;
            }
            set {
                this.paxCarrier3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxCarrier4 {
            get {
                return this.paxCarrier4Field;
            }
            set {
                this.paxCarrier4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxClass1 {
            get {
                return this.paxClass1Field;
            }
            set {
                this.paxClass1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxClass2 {
            get {
                return this.paxClass2Field;
            }
            set {
                this.paxClass2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxClass3 {
            get {
                return this.paxClass3Field;
            }
            set {
                this.paxClass3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxClass4 {
            get {
                return this.paxClass4Field;
            }
            set {
                this.paxClass4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxDate2 {
            get {
                return this.paxDate2Field;
            }
            set {
                this.paxDate2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxDate3 {
            get {
                return this.paxDate3Field;
            }
            set {
                this.paxDate3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxDate4 {
            get {
                return this.paxDate4Field;
            }
            set {
                this.paxDate4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxDateDepart {
            get {
                return this.paxDateDepartField;
            }
            set {
                this.paxDateDepartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxFareBasis1 {
            get {
                return this.paxFareBasis1Field;
            }
            set {
                this.paxFareBasis1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxFareBasis2 {
            get {
                return this.paxFareBasis2Field;
            }
            set {
                this.paxFareBasis2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxFareBasis3 {
            get {
                return this.paxFareBasis3Field;
            }
            set {
                this.paxFareBasis3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxFareBasis4 {
            get {
                return this.paxFareBasis4Field;
            }
            set {
                this.paxFareBasis4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxFlightNumber1 {
            get {
                return this.paxFlightNumber1Field;
            }
            set {
                this.paxFlightNumber1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxFlightNumber2 {
            get {
                return this.paxFlightNumber2Field;
            }
            set {
                this.paxFlightNumber2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxFlightNumber3 {
            get {
                return this.paxFlightNumber3Field;
            }
            set {
                this.paxFlightNumber3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxFlightNumber4 {
            get {
                return this.paxFlightNumber4Field;
            }
            set {
                this.paxFlightNumber4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxLeg1 {
            get {
                return this.paxLeg1Field;
            }
            set {
                this.paxLeg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxLeg2 {
            get {
                return this.paxLeg2Field;
            }
            set {
                this.paxLeg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxLeg3 {
            get {
                return this.paxLeg3Field;
            }
            set {
                this.paxLeg3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxLeg4 {
            get {
                return this.paxLeg4Field;
            }
            set {
                this.paxLeg4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxName {
            get {
                return this.paxNameField;
            }
            set {
                this.paxNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxOrigin {
            get {
                return this.paxOriginField;
            }
            set {
                this.paxOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxStopOverCode1 {
            get {
                return this.paxStopOverCode1Field;
            }
            set {
                this.paxStopOverCode1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxStopOverCode2 {
            get {
                return this.paxStopOverCode2Field;
            }
            set {
                this.paxStopOverCode2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxStopOverCode3 {
            get {
                return this.paxStopOverCode3Field;
            }
            set {
                this.paxStopOverCode3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxStopOverCode4 {
            get {
                return this.paxStopOverCode4Field;
            }
            set {
                this.paxStopOverCode4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxTicketNumber {
            get {
                return this.paxTicketNumberField;
            }
            set {
                this.paxTicketNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxTime1 {
            get {
                return this.paxTime1Field;
            }
            set {
                this.paxTime1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxTime2 {
            get {
                return this.paxTime2Field;
            }
            set {
                this.paxTime2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxTime3 {
            get {
                return this.paxTime3Field;
            }
            set {
                this.paxTime3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxTime4 {
            get {
                return this.paxTime4Field;
            }
            set {
                this.paxTime4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string paxTravelAgentInfo {
            get {
                return this.paxTravelAgentInfoField;
            }
            set {
                this.paxTravelAgentInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnUrl {
            get {
                return this.returnUrlField;
            }
            set {
                this.returnUrlField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeoutSpecified {
            get {
                return this.timeoutFieldSpecified;
            }
            set {
                this.timeoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public transactionDetailsField[] transactionDetailsFields {
            get {
                return this.transactionDetailsFieldsField;
            }
            set {
                this.transactionDetailsFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnData1 {
            get {
                return this.txnData1Field;
            }
            set {
                this.txnData1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnData2 {
            get {
                return this.txnData2Field;
            }
            set {
                this.txnData2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnData3 {
            get {
                return this.txnData3Field;
            }
            set {
                this.txnData3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnRef {
            get {
                return this.txnRefField;
            }
            set {
                this.txnRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnType {
            get {
                return this.txnTypeField;
            }
            set {
                this.txnTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class transactionDetailsField : NameValueField {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transactionResultField))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transactionDetailsField))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class NameValueField {
        
        private string fieldNameField;
        
        private string fieldValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fieldValue {
            get {
                return this.fieldValueField;
            }
            set {
                this.fieldValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class riskRuleMatch {
        
        private string actionField;
        
        private string amountLimitField;
        
        private string includedTransactionsField;
        
        private string matchedAmountField;
        
        private int matchedTransactionCountField;
        
        private bool matchedTransactionCountFieldSpecified;
        
        private string nameField;
        
        private int periodField;
        
        private bool periodFieldSpecified;
        
        private int transactionCountLimitField;
        
        private bool transactionCountLimitFieldSpecified;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountLimit {
            get {
                return this.amountLimitField;
            }
            set {
                this.amountLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string includedTransactions {
            get {
                return this.includedTransactionsField;
            }
            set {
                this.includedTransactionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string matchedAmount {
            get {
                return this.matchedAmountField;
            }
            set {
                this.matchedAmountField = value;
            }
        }
        
        /// <remarks/>
        public int matchedTransactionCount {
            get {
                return this.matchedTransactionCountField;
            }
            set {
                this.matchedTransactionCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool matchedTransactionCountSpecified {
            get {
                return this.matchedTransactionCountFieldSpecified;
            }
            set {
                this.matchedTransactionCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodSpecified {
            get {
                return this.periodFieldSpecified;
            }
            set {
                this.periodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int transactionCountLimit {
            get {
                return this.transactionCountLimitField;
            }
            set {
                this.transactionCountLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionCountLimitSpecified {
            get {
                return this.transactionCountLimitFieldSpecified;
            }
            set {
                this.transactionCountLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paymentexpress.com")]
    public partial class TransactionResult {
        
        private string amountField;
        
        private string authCodeField;
        
        private string billingIdField;
        
        private string cardHolderNameField;
        
        private string cardNameField;
        
        private string cardNumberField;
        
        private string cardNumber2Field;
        
        private string currencyIdField;
        
        private string currencyNameField;
        
        private string currencyRateField;
        
        private string cvc2ResultCodeField;
        
        private string dateExpiryField;
        
        private System.DateTime dateSettlementField;
        
        private bool dateSettlementFieldSpecified;
        
        private string dpsBillingIdField;
        
        private string dpsTxnRefField;
        
        private string merchantReferenceField;
        
        private string responseCodeField;
        
        private string responseTextField;
        
        private riskRuleMatch[] riskRuleMatchesField;
        
        private string sessionIdField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private bool testModeField;
        
        private bool testModeFieldSpecified;
        
        private string transactionIdField;
        
        private transactionResultField[] transactionResultFieldsField;
        
        private string txnData1Field;
        
        private string txnData2Field;
        
        private string txnData3Field;
        
        private string txnMacField;
        
        private string txnRefField;
        
        private string txnTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string billingId {
            get {
                return this.billingIdField;
            }
            set {
                this.billingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardName {
            get {
                return this.cardNameField;
            }
            set {
                this.cardNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardNumber2 {
            get {
                return this.cardNumber2Field;
            }
            set {
                this.cardNumber2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currencyId {
            get {
                return this.currencyIdField;
            }
            set {
                this.currencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currencyName {
            get {
                return this.currencyNameField;
            }
            set {
                this.currencyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currencyRate {
            get {
                return this.currencyRateField;
            }
            set {
                this.currencyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cvc2ResultCode {
            get {
                return this.cvc2ResultCodeField;
            }
            set {
                this.cvc2ResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dateExpiry {
            get {
                return this.dateExpiryField;
            }
            set {
                this.dateExpiryField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateSettlement {
            get {
                return this.dateSettlementField;
            }
            set {
                this.dateSettlementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSettlementSpecified {
            get {
                return this.dateSettlementFieldSpecified;
            }
            set {
                this.dateSettlementFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dpsBillingId {
            get {
                return this.dpsBillingIdField;
            }
            set {
                this.dpsBillingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dpsTxnRef {
            get {
                return this.dpsTxnRefField;
            }
            set {
                this.dpsTxnRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantReference {
            get {
                return this.merchantReferenceField;
            }
            set {
                this.merchantReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string responseText {
            get {
                return this.responseTextField;
            }
            set {
                this.responseTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public riskRuleMatch[] riskRuleMatches {
            get {
                return this.riskRuleMatchesField;
            }
            set {
                this.riskRuleMatchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool testMode {
            get {
                return this.testModeField;
            }
            set {
                this.testModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool testModeSpecified {
            get {
                return this.testModeFieldSpecified;
            }
            set {
                this.testModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public transactionResultField[] transactionResultFields {
            get {
                return this.transactionResultFieldsField;
            }
            set {
                this.transactionResultFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnData1 {
            get {
                return this.txnData1Field;
            }
            set {
                this.txnData1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnData2 {
            get {
                return this.txnData2Field;
            }
            set {
                this.txnData2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnData3 {
            get {
                return this.txnData3Field;
            }
            set {
                this.txnData3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnMac {
            get {
                return this.txnMacField;
            }
            set {
                this.txnMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnRef {
            get {
                return this.txnRefField;
            }
            set {
                this.txnRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string txnType {
            get {
                return this.txnTypeField;
            }
            set {
                this.txnTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class transactionResultField : NameValueField {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TransactionId {
        
        private string sessionIdField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTransactionIdCompletedEventHandler(object sender, GetTransactionIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionId Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionId)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CancelTransactionCompletedEventHandler(object sender, CancelTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool CancelTransactionResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CancelTransactionResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTransactionCompletedEventHandler(object sender, GetTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591